// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        (unknown)
// source: key_protection_service/proto/api.proto

package kpspb

import (
	_ "buf.build/gen/go/bufbuild/protovalidate/protocolbuffers/go/buf/validate"
	proto "github.com/GoogleCloudPlatform/key-protection-module/km_common/proto"
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type GenerateKEMKeypairRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Algo          *proto.HpkeAlgorithm   `protobuf:"bytes,1,opt,name=algo,proto3" json:"algo,omitempty"`
	BindingPubKey *proto.HpkePublicKey   `protobuf:"bytes,2,opt,name=binding_pub_key,json=bindingPubKey,proto3" json:"binding_pub_key,omitempty"`
	LifespanSecs  uint64                 `protobuf:"varint,3,opt,name=lifespan_secs,json=lifespanSecs,proto3" json:"lifespan_secs,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateKEMKeypairRequest) Reset() {
	*x = GenerateKEMKeypairRequest{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKEMKeypairRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKEMKeypairRequest) ProtoMessage() {}

func (x *GenerateKEMKeypairRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKEMKeypairRequest.ProtoReflect.Descriptor instead.
func (*GenerateKEMKeypairRequest) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{0}
}

func (x *GenerateKEMKeypairRequest) GetAlgo() *proto.HpkeAlgorithm {
	if x != nil {
		return x.Algo
	}
	return nil
}

func (x *GenerateKEMKeypairRequest) GetBindingPubKey() *proto.HpkePublicKey {
	if x != nil {
		return x.BindingPubKey
	}
	return nil
}

func (x *GenerateKEMKeypairRequest) GetLifespanSecs() uint64 {
	if x != nil {
		return x.LifespanSecs
	}
	return 0
}

type GenerateKEMKeypairResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyHandle     *proto.KeyHandle       `protobuf:"bytes,1,opt,name=key_handle,json=keyHandle,proto3" json:"key_handle,omitempty"`
	KemPubKey     *proto.KemPublicKey    `protobuf:"bytes,2,opt,name=kem_pub_key,json=kemPubKey,proto3" json:"kem_pub_key,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GenerateKEMKeypairResponse) Reset() {
	*x = GenerateKEMKeypairResponse{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GenerateKEMKeypairResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GenerateKEMKeypairResponse) ProtoMessage() {}

func (x *GenerateKEMKeypairResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GenerateKEMKeypairResponse.ProtoReflect.Descriptor instead.
func (*GenerateKEMKeypairResponse) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{1}
}

func (x *GenerateKEMKeypairResponse) GetKeyHandle() *proto.KeyHandle {
	if x != nil {
		return x.KeyHandle
	}
	return nil
}

func (x *GenerateKEMKeypairResponse) GetKemPubKey() *proto.KemPublicKey {
	if x != nil {
		return x.KemPubKey
	}
	return nil
}

type DecapAndSealRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyHandle     *proto.KeyHandle       `protobuf:"bytes,1,opt,name=key_handle,json=keyHandle,proto3" json:"key_handle,omitempty"`
	Ciphertext    *proto.KemCiphertext   `protobuf:"bytes,2,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Aad           []byte                 `protobuf:"bytes,3,opt,name=aad,proto3" json:"aad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecapAndSealRequest) Reset() {
	*x = DecapAndSealRequest{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecapAndSealRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecapAndSealRequest) ProtoMessage() {}

func (x *DecapAndSealRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecapAndSealRequest.ProtoReflect.Descriptor instead.
func (*DecapAndSealRequest) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{2}
}

func (x *DecapAndSealRequest) GetKeyHandle() *proto.KeyHandle {
	if x != nil {
		return x.KeyHandle
	}
	return nil
}

func (x *DecapAndSealRequest) GetCiphertext() *proto.KemCiphertext {
	if x != nil {
		return x.Ciphertext
	}
	return nil
}

func (x *DecapAndSealRequest) GetAad() []byte {
	if x != nil {
		return x.Aad
	}
	return nil
}

type DecapAndSealResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SealEnc       []byte                 `protobuf:"bytes,1,opt,name=seal_enc,json=sealEnc,proto3" json:"seal_enc,omitempty"`
	SealedCt      []byte                 `protobuf:"bytes,2,opt,name=sealed_ct,json=sealedCt,proto3" json:"sealed_ct,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecapAndSealResponse) Reset() {
	*x = DecapAndSealResponse{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecapAndSealResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecapAndSealResponse) ProtoMessage() {}

func (x *DecapAndSealResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecapAndSealResponse.ProtoReflect.Descriptor instead.
func (*DecapAndSealResponse) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{3}
}

func (x *DecapAndSealResponse) GetSealEnc() []byte {
	if x != nil {
		return x.SealEnc
	}
	return nil
}

func (x *DecapAndSealResponse) GetSealedCt() []byte {
	if x != nil {
		return x.SealedCt
	}
	return nil
}

type EnumerateKEMKeysRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Limit         int32                  `protobuf:"varint,1,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,2,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumerateKEMKeysRequest) Reset() {
	*x = EnumerateKEMKeysRequest{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumerateKEMKeysRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerateKEMKeysRequest) ProtoMessage() {}

func (x *EnumerateKEMKeysRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerateKEMKeysRequest.ProtoReflect.Descriptor instead.
func (*EnumerateKEMKeysRequest) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{4}
}

func (x *EnumerateKEMKeysRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *EnumerateKEMKeysRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type KEMKeyInfo struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	KeyHandle             *proto.KeyHandle       `protobuf:"bytes,1,opt,name=key_handle,json=keyHandle,proto3" json:"key_handle,omitempty"`
	Algorithm             *proto.HpkeAlgorithm   `protobuf:"bytes,2,opt,name=algorithm,proto3" json:"algorithm,omitempty"`
	KemPubKey             []byte                 `protobuf:"bytes,3,opt,name=kem_pub_key,json=kemPubKey,proto3" json:"kem_pub_key,omitempty"`
	RemainingLifespanSecs uint64                 `protobuf:"varint,4,opt,name=remaining_lifespan_secs,json=remainingLifespanSecs,proto3" json:"remaining_lifespan_secs,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *KEMKeyInfo) Reset() {
	*x = KEMKeyInfo{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *KEMKeyInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*KEMKeyInfo) ProtoMessage() {}

func (x *KEMKeyInfo) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use KEMKeyInfo.ProtoReflect.Descriptor instead.
func (*KEMKeyInfo) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{5}
}

func (x *KEMKeyInfo) GetKeyHandle() *proto.KeyHandle {
	if x != nil {
		return x.KeyHandle
	}
	return nil
}

func (x *KEMKeyInfo) GetAlgorithm() *proto.HpkeAlgorithm {
	if x != nil {
		return x.Algorithm
	}
	return nil
}

func (x *KEMKeyInfo) GetKemPubKey() []byte {
	if x != nil {
		return x.KemPubKey
	}
	return nil
}

func (x *KEMKeyInfo) GetRemainingLifespanSecs() uint64 {
	if x != nil {
		return x.RemainingLifespanSecs
	}
	return 0
}

type EnumerateKEMKeysResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Keys          []*KEMKeyInfo          `protobuf:"bytes,1,rep,name=keys,proto3" json:"keys,omitempty"`
	HasMore       bool                   `protobuf:"varint,2,opt,name=has_more,json=hasMore,proto3" json:"has_more,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EnumerateKEMKeysResponse) Reset() {
	*x = EnumerateKEMKeysResponse{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EnumerateKEMKeysResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EnumerateKEMKeysResponse) ProtoMessage() {}

func (x *EnumerateKEMKeysResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EnumerateKEMKeysResponse.ProtoReflect.Descriptor instead.
func (*EnumerateKEMKeysResponse) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{6}
}

func (x *EnumerateKEMKeysResponse) GetKeys() []*KEMKeyInfo {
	if x != nil {
		return x.Keys
	}
	return nil
}

func (x *EnumerateKEMKeysResponse) GetHasMore() bool {
	if x != nil {
		return x.HasMore
	}
	return false
}

type DestroyKEMKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyHandle     *proto.KeyHandle       `protobuf:"bytes,1,opt,name=key_handle,json=keyHandle,proto3" json:"key_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyKEMKeyRequest) Reset() {
	*x = DestroyKEMKeyRequest{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyKEMKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyKEMKeyRequest) ProtoMessage() {}

func (x *DestroyKEMKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyKEMKeyRequest.ProtoReflect.Descriptor instead.
func (*DestroyKEMKeyRequest) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{7}
}

func (x *DestroyKEMKeyRequest) GetKeyHandle() *proto.KeyHandle {
	if x != nil {
		return x.KeyHandle
	}
	return nil
}

type DestroyKEMKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DestroyKEMKeyResponse) Reset() {
	*x = DestroyKEMKeyResponse{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DestroyKEMKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DestroyKEMKeyResponse) ProtoMessage() {}

func (x *DestroyKEMKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DestroyKEMKeyResponse.ProtoReflect.Descriptor instead.
func (*DestroyKEMKeyResponse) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{8}
}

type GetKEMKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyHandle     *proto.KeyHandle       `protobuf:"bytes,1,opt,name=key_handle,json=keyHandle,proto3" json:"key_handle,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKEMKeyRequest) Reset() {
	*x = GetKEMKeyRequest{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKEMKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKEMKeyRequest) ProtoMessage() {}

func (x *GetKEMKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKEMKeyRequest.ProtoReflect.Descriptor instead.
func (*GetKEMKeyRequest) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{9}
}

func (x *GetKEMKeyRequest) GetKeyHandle() *proto.KeyHandle {
	if x != nil {
		return x.KeyHandle
	}
	return nil
}

type GetKEMKeyResponse struct {
	state                 protoimpl.MessageState `protogen:"open.v1"`
	KemPubKey             *proto.KemPublicKey    `protobuf:"bytes,1,opt,name=kem_pub_key,json=kemPubKey,proto3" json:"kem_pub_key,omitempty"`
	BindingPubKey         *proto.HpkePublicKey   `protobuf:"bytes,2,opt,name=binding_pub_key,json=bindingPubKey,proto3" json:"binding_pub_key,omitempty"`
	RemainingLifespanSecs uint64                 `protobuf:"varint,3,opt,name=remaining_lifespan_secs,json=remainingLifespanSecs,proto3" json:"remaining_lifespan_secs,omitempty"`
	unknownFields         protoimpl.UnknownFields
	sizeCache             protoimpl.SizeCache
}

func (x *GetKEMKeyResponse) Reset() {
	*x = GetKEMKeyResponse{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKEMKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKEMKeyResponse) ProtoMessage() {}

func (x *GetKEMKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKEMKeyResponse.ProtoReflect.Descriptor instead.
func (*GetKEMKeyResponse) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{10}
}

func (x *GetKEMKeyResponse) GetKemPubKey() *proto.KemPublicKey {
	if x != nil {
		return x.KemPubKey
	}
	return nil
}

func (x *GetKEMKeyResponse) GetBindingPubKey() *proto.HpkePublicKey {
	if x != nil {
		return x.BindingPubKey
	}
	return nil
}

func (x *GetKEMKeyResponse) GetRemainingLifespanSecs() uint64 {
	if x != nil {
		return x.RemainingLifespanSecs
	}
	return 0
}

type HeartbeatRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatRequest) Reset() {
	*x = HeartbeatRequest{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatRequest) ProtoMessage() {}

func (x *HeartbeatRequest) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatRequest.ProtoReflect.Descriptor instead.
func (*HeartbeatRequest) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{11}
}

type HeartbeatResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KpsBootToken  string                 `protobuf:"bytes,1,opt,name=kps_boot_token,json=kpsBootToken,proto3" json:"kps_boot_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *HeartbeatResponse) Reset() {
	*x = HeartbeatResponse{}
	mi := &file_key_protection_service_proto_api_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *HeartbeatResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*HeartbeatResponse) ProtoMessage() {}

func (x *HeartbeatResponse) ProtoReflect() protoreflect.Message {
	mi := &file_key_protection_service_proto_api_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use HeartbeatResponse.ProtoReflect.Descriptor instead.
func (*HeartbeatResponse) Descriptor() ([]byte, []int) {
	return file_key_protection_service_proto_api_proto_rawDescGZIP(), []int{12}
}

func (x *HeartbeatResponse) GetKpsBootToken() string {
	if x != nil {
		return x.KpsBootToken
	}
	return ""
}

var File_key_protection_service_proto_api_proto protoreflect.FileDescriptor

const file_key_protection_service_proto_api_proto_rawDesc = "" +
	"\n" +
	"&key_protection_service/proto/api.proto\x12!keymanager.key_protection_service\x1a\x1bbuf/validate/validate.proto\x1a km_common/proto/algorithms.proto\x1a\"km_common/proto/crypto_types.proto\x1a km_common/proto/key_claims.proto\x1a\x1dkm_common/proto/payload.proto\"\xba\x01\n" +
	"\x19GenerateKEMKeypairRequest\x125\n" +
	"\x04algo\x18\x01 \x01(\v2\x19.keymanager.HpkeAlgorithmB\x06\xbaH\x03\xc8\x01\x01R\x04algo\x12A\n" +
	"\x0fbinding_pub_key\x18\x02 \x01(\v2\x19.keymanager.HpkePublicKeyR\rbindingPubKey\x12#\n" +
	"\rlifespan_secs\x18\x03 \x01(\x04R\flifespanSecs\"\x8c\x01\n" +
	"\x1aGenerateKEMKeypairResponse\x124\n" +
	"\n" +
	"key_handle\x18\x01 \x01(\v2\x15.keymanager.KeyHandleR\tkeyHandle\x128\n" +
	"\vkem_pub_key\x18\x02 \x01(\v2\x18.keymanager.KemPublicKeyR\tkemPubKey\"\xa0\x01\n" +
	"\x13DecapAndSealRequest\x12<\n" +
	"\n" +
	"key_handle\x18\x01 \x01(\v2\x15.keymanager.KeyHandleB\x06\xbaH\x03\xc8\x01\x01R\tkeyHandle\x129\n" +
	"\n" +
	"ciphertext\x18\x02 \x01(\v2\x19.keymanager.KemCiphertextR\n" +
	"ciphertext\x12\x10\n" +
	"\x03aad\x18\x03 \x01(\fR\x03aad\"N\n" +
	"\x14DecapAndSealResponse\x12\x19\n" +
	"\bseal_enc\x18\x01 \x01(\fR\asealEnc\x12\x1b\n" +
	"\tsealed_ct\x18\x02 \x01(\fR\bsealedCt\"[\n" +
	"\x17EnumerateKEMKeysRequest\x12\x1f\n" +
	"\x05limit\x18\x01 \x01(\x05B\t\xbaH\x06\x1a\x04\x18d \x00R\x05limit\x12\x1f\n" +
	"\x06offset\x18\x02 \x01(\x05B\a\xbaH\x04\x1a\x02(\x00R\x06offset\"\xd3\x01\n" +
	"\n" +
	"KEMKeyInfo\x124\n" +
	"\n" +
	"key_handle\x18\x01 \x01(\v2\x15.keymanager.KeyHandleR\tkeyHandle\x127\n" +
	"\talgorithm\x18\x02 \x01(\v2\x19.keymanager.HpkeAlgorithmR\talgorithm\x12\x1e\n" +
	"\vkem_pub_key\x18\x03 \x01(\fR\tkemPubKey\x126\n" +
	"\x17remaining_lifespan_secs\x18\x04 \x01(\x04R\x15remainingLifespanSecs\"x\n" +
	"\x18EnumerateKEMKeysResponse\x12A\n" +
	"\x04keys\x18\x01 \x03(\v2-.keymanager.key_protection_service.KEMKeyInfoR\x04keys\x12\x19\n" +
	"\bhas_more\x18\x02 \x01(\bR\ahasMore\"T\n" +
	"\x14DestroyKEMKeyRequest\x12<\n" +
	"\n" +
	"key_handle\x18\x01 \x01(\v2\x15.keymanager.KeyHandleB\x06\xbaH\x03\xc8\x01\x01R\tkeyHandle\"\x17\n" +
	"\x15DestroyKEMKeyResponse\"P\n" +
	"\x10GetKEMKeyRequest\x12<\n" +
	"\n" +
	"key_handle\x18\x01 \x01(\v2\x15.keymanager.KeyHandleB\x06\xbaH\x03\xc8\x01\x01R\tkeyHandle\"\xc8\x01\n" +
	"\x11GetKEMKeyResponse\x128\n" +
	"\vkem_pub_key\x18\x01 \x01(\v2\x18.keymanager.KemPublicKeyR\tkemPubKey\x12A\n" +
	"\x0fbinding_pub_key\x18\x02 \x01(\v2\x19.keymanager.HpkePublicKeyR\rbindingPubKey\x126\n" +
	"\x17remaining_lifespan_secs\x18\x03 \x01(\x04R\x15remainingLifespanSecs\"\x12\n" +
	"\x10HeartbeatRequest\"9\n" +
	"\x11HeartbeatResponse\x12$\n" +
	"\x0ekps_boot_token\x18\x01 \x01(\tR\fkpsBootToken2\xae\x06\n" +
	"\x14KeyProtectionService\x12\x91\x01\n" +
	"\x12GenerateKEMKeypair\x12<.keymanager.key_protection_service.GenerateKEMKeypairRequest\x1a=.keymanager.key_protection_service.GenerateKEMKeypairResponse\x12\x7f\n" +
	"\fDecapAndSeal\x126.keymanager.key_protection_service.DecapAndSealRequest\x1a7.keymanager.key_protection_service.DecapAndSealResponse\x12\x8b\x01\n" +
	"\x10EnumerateKEMKeys\x12:.keymanager.key_protection_service.EnumerateKEMKeysRequest\x1a;.keymanager.key_protection_service.EnumerateKEMKeysResponse\x12\x82\x01\n" +
	"\rDestroyKEMKey\x127.keymanager.key_protection_service.DestroyKEMKeyRequest\x1a8.keymanager.key_protection_service.DestroyKEMKeyResponse\x12v\n" +
	"\tGetKEMKey\x123.keymanager.key_protection_service.GetKEMKeyRequest\x1a4.keymanager.key_protection_service.GetKEMKeyResponse\x12v\n" +
	"\tHeartbeat\x123.keymanager.key_protection_service.HeartbeatRequest\x1a4.keymanager.key_protection_service.HeartbeatResponseBYZWgithub.com/GoogleCloudPlatform/key-protection-module/key_protection_service/proto;kpspbb\x06proto3"

var (
	file_key_protection_service_proto_api_proto_rawDescOnce sync.Once
	file_key_protection_service_proto_api_proto_rawDescData []byte
)

func file_key_protection_service_proto_api_proto_rawDescGZIP() []byte {
	file_key_protection_service_proto_api_proto_rawDescOnce.Do(func() {
		file_key_protection_service_proto_api_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_key_protection_service_proto_api_proto_rawDesc), len(file_key_protection_service_proto_api_proto_rawDesc)))
	})
	return file_key_protection_service_proto_api_proto_rawDescData
}

var file_key_protection_service_proto_api_proto_msgTypes = make([]protoimpl.MessageInfo, 13)
var file_key_protection_service_proto_api_proto_goTypes = []any{
	(*GenerateKEMKeypairRequest)(nil),  // 0: keymanager.key_protection_service.GenerateKEMKeypairRequest
	(*GenerateKEMKeypairResponse)(nil), // 1: keymanager.key_protection_service.GenerateKEMKeypairResponse
	(*DecapAndSealRequest)(nil),        // 2: keymanager.key_protection_service.DecapAndSealRequest
	(*DecapAndSealResponse)(nil),       // 3: keymanager.key_protection_service.DecapAndSealResponse
	(*EnumerateKEMKeysRequest)(nil),    // 4: keymanager.key_protection_service.EnumerateKEMKeysRequest
	(*KEMKeyInfo)(nil),                 // 5: keymanager.key_protection_service.KEMKeyInfo
	(*EnumerateKEMKeysResponse)(nil),   // 6: keymanager.key_protection_service.EnumerateKEMKeysResponse
	(*DestroyKEMKeyRequest)(nil),       // 7: keymanager.key_protection_service.DestroyKEMKeyRequest
	(*DestroyKEMKeyResponse)(nil),      // 8: keymanager.key_protection_service.DestroyKEMKeyResponse
	(*GetKEMKeyRequest)(nil),           // 9: keymanager.key_protection_service.GetKEMKeyRequest
	(*GetKEMKeyResponse)(nil),          // 10: keymanager.key_protection_service.GetKEMKeyResponse
	(*HeartbeatRequest)(nil),           // 11: keymanager.key_protection_service.HeartbeatRequest
	(*HeartbeatResponse)(nil),          // 12: keymanager.key_protection_service.HeartbeatResponse
	(*proto.HpkeAlgorithm)(nil),        // 13: keymanager.HpkeAlgorithm
	(*proto.HpkePublicKey)(nil),        // 14: keymanager.HpkePublicKey
	(*proto.KeyHandle)(nil),            // 15: keymanager.KeyHandle
	(*proto.KemPublicKey)(nil),         // 16: keymanager.KemPublicKey
	(*proto.KemCiphertext)(nil),        // 17: keymanager.KemCiphertext
}
var file_key_protection_service_proto_api_proto_depIdxs = []int32{
	13, // 0: keymanager.key_protection_service.GenerateKEMKeypairRequest.algo:type_name -> keymanager.HpkeAlgorithm
	14, // 1: keymanager.key_protection_service.GenerateKEMKeypairRequest.binding_pub_key:type_name -> keymanager.HpkePublicKey
	15, // 2: keymanager.key_protection_service.GenerateKEMKeypairResponse.key_handle:type_name -> keymanager.KeyHandle
	16, // 3: keymanager.key_protection_service.GenerateKEMKeypairResponse.kem_pub_key:type_name -> keymanager.KemPublicKey
	15, // 4: keymanager.key_protection_service.DecapAndSealRequest.key_handle:type_name -> keymanager.KeyHandle
	17, // 5: keymanager.key_protection_service.DecapAndSealRequest.ciphertext:type_name -> keymanager.KemCiphertext
	15, // 6: keymanager.key_protection_service.KEMKeyInfo.key_handle:type_name -> keymanager.KeyHandle
	13, // 7: keymanager.key_protection_service.KEMKeyInfo.algorithm:type_name -> keymanager.HpkeAlgorithm
	5,  // 8: keymanager.key_protection_service.EnumerateKEMKeysResponse.keys:type_name -> keymanager.key_protection_service.KEMKeyInfo
	15, // 9: keymanager.key_protection_service.DestroyKEMKeyRequest.key_handle:type_name -> keymanager.KeyHandle
	15, // 10: keymanager.key_protection_service.GetKEMKeyRequest.key_handle:type_name -> keymanager.KeyHandle
	16, // 11: keymanager.key_protection_service.GetKEMKeyResponse.kem_pub_key:type_name -> keymanager.KemPublicKey
	14, // 12: keymanager.key_protection_service.GetKEMKeyResponse.binding_pub_key:type_name -> keymanager.HpkePublicKey
	0,  // 13: keymanager.key_protection_service.KeyProtectionService.GenerateKEMKeypair:input_type -> keymanager.key_protection_service.GenerateKEMKeypairRequest
	2,  // 14: keymanager.key_protection_service.KeyProtectionService.DecapAndSeal:input_type -> keymanager.key_protection_service.DecapAndSealRequest
	4,  // 15: keymanager.key_protection_service.KeyProtectionService.EnumerateKEMKeys:input_type -> keymanager.key_protection_service.EnumerateKEMKeysRequest
	7,  // 16: keymanager.key_protection_service.KeyProtectionService.DestroyKEMKey:input_type -> keymanager.key_protection_service.DestroyKEMKeyRequest
	9,  // 17: keymanager.key_protection_service.KeyProtectionService.GetKEMKey:input_type -> keymanager.key_protection_service.GetKEMKeyRequest
	11, // 18: keymanager.key_protection_service.KeyProtectionService.Heartbeat:input_type -> keymanager.key_protection_service.HeartbeatRequest
	1,  // 19: keymanager.key_protection_service.KeyProtectionService.GenerateKEMKeypair:output_type -> keymanager.key_protection_service.GenerateKEMKeypairResponse
	3,  // 20: keymanager.key_protection_service.KeyProtectionService.DecapAndSeal:output_type -> keymanager.key_protection_service.DecapAndSealResponse
	6,  // 21: keymanager.key_protection_service.KeyProtectionService.EnumerateKEMKeys:output_type -> keymanager.key_protection_service.EnumerateKEMKeysResponse
	8,  // 22: keymanager.key_protection_service.KeyProtectionService.DestroyKEMKey:output_type -> keymanager.key_protection_service.DestroyKEMKeyResponse
	10, // 23: keymanager.key_protection_service.KeyProtectionService.GetKEMKey:output_type -> keymanager.key_protection_service.GetKEMKeyResponse
	12, // 24: keymanager.key_protection_service.KeyProtectionService.Heartbeat:output_type -> keymanager.key_protection_service.HeartbeatResponse
	19, // [19:25] is the sub-list for method output_type
	13, // [13:19] is the sub-list for method input_type
	13, // [13:13] is the sub-list for extension type_name
	13, // [13:13] is the sub-list for extension extendee
	0,  // [0:13] is the sub-list for field type_name
}

func init() { file_key_protection_service_proto_api_proto_init() }
func file_key_protection_service_proto_api_proto_init() {
	if File_key_protection_service_proto_api_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_key_protection_service_proto_api_proto_rawDesc), len(file_key_protection_service_proto_api_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   13,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_key_protection_service_proto_api_proto_goTypes,
		DependencyIndexes: file_key_protection_service_proto_api_proto_depIdxs,
		MessageInfos:      file_key_protection_service_proto_api_proto_msgTypes,
	}.Build()
	File_key_protection_service_proto_api_proto = out.File
	file_key_protection_service_proto_api_proto_goTypes = nil
	file_key_protection_service_proto_api_proto_depIdxs = nil
}
