// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: key_protection_service/proto/api.proto

package kpspb

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyProtectionService_GenerateKEMKeypair_FullMethodName = "/keymanager.key_protection_service.KeyProtectionService/GenerateKEMKeypair"
	KeyProtectionService_DecapAndSeal_FullMethodName       = "/keymanager.key_protection_service.KeyProtectionService/DecapAndSeal"
	KeyProtectionService_EnumerateKEMKeys_FullMethodName   = "/keymanager.key_protection_service.KeyProtectionService/EnumerateKEMKeys"
	KeyProtectionService_DestroyKEMKey_FullMethodName      = "/keymanager.key_protection_service.KeyProtectionService/DestroyKEMKey"
	KeyProtectionService_GetKEMKey_FullMethodName          = "/keymanager.key_protection_service.KeyProtectionService/GetKEMKey"
	KeyProtectionService_Heartbeat_FullMethodName          = "/keymanager.key_protection_service.KeyProtectionService/Heartbeat"
)

// KeyProtectionServiceClient is the client API for KeyProtectionService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
type KeyProtectionServiceClient interface {
	GenerateKEMKeypair(ctx context.Context, in *GenerateKEMKeypairRequest, opts ...grpc.CallOption) (*GenerateKEMKeypairResponse, error)
	DecapAndSeal(ctx context.Context, in *DecapAndSealRequest, opts ...grpc.CallOption) (*DecapAndSealResponse, error)
	EnumerateKEMKeys(ctx context.Context, in *EnumerateKEMKeysRequest, opts ...grpc.CallOption) (*EnumerateKEMKeysResponse, error)
	DestroyKEMKey(ctx context.Context, in *DestroyKEMKeyRequest, opts ...grpc.CallOption) (*DestroyKEMKeyResponse, error)
	GetKEMKey(ctx context.Context, in *GetKEMKeyRequest, opts ...grpc.CallOption) (*GetKEMKeyResponse, error)
	Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error)
}

type keyProtectionServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyProtectionServiceClient(cc grpc.ClientConnInterface) KeyProtectionServiceClient {
	return &keyProtectionServiceClient{cc}
}

func (c *keyProtectionServiceClient) GenerateKEMKeypair(ctx context.Context, in *GenerateKEMKeypairRequest, opts ...grpc.CallOption) (*GenerateKEMKeypairResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GenerateKEMKeypairResponse)
	err := c.cc.Invoke(ctx, KeyProtectionService_GenerateKEMKeypair_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyProtectionServiceClient) DecapAndSeal(ctx context.Context, in *DecapAndSealRequest, opts ...grpc.CallOption) (*DecapAndSealResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecapAndSealResponse)
	err := c.cc.Invoke(ctx, KeyProtectionService_DecapAndSeal_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyProtectionServiceClient) EnumerateKEMKeys(ctx context.Context, in *EnumerateKEMKeysRequest, opts ...grpc.CallOption) (*EnumerateKEMKeysResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EnumerateKEMKeysResponse)
	err := c.cc.Invoke(ctx, KeyProtectionService_EnumerateKEMKeys_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyProtectionServiceClient) DestroyKEMKey(ctx context.Context, in *DestroyKEMKeyRequest, opts ...grpc.CallOption) (*DestroyKEMKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DestroyKEMKeyResponse)
	err := c.cc.Invoke(ctx, KeyProtectionService_DestroyKEMKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyProtectionServiceClient) GetKEMKey(ctx context.Context, in *GetKEMKeyRequest, opts ...grpc.CallOption) (*GetKEMKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKEMKeyResponse)
	err := c.cc.Invoke(ctx, KeyProtectionService_GetKEMKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *keyProtectionServiceClient) Heartbeat(ctx context.Context, in *HeartbeatRequest, opts ...grpc.CallOption) (*HeartbeatResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(HeartbeatResponse)
	err := c.cc.Invoke(ctx, KeyProtectionService_Heartbeat_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyProtectionServiceServer is the server API for KeyProtectionService service.
// All implementations should embed UnimplementedKeyProtectionServiceServer
// for forward compatibility.
type KeyProtectionServiceServer interface {
	GenerateKEMKeypair(context.Context, *GenerateKEMKeypairRequest) (*GenerateKEMKeypairResponse, error)
	DecapAndSeal(context.Context, *DecapAndSealRequest) (*DecapAndSealResponse, error)
	EnumerateKEMKeys(context.Context, *EnumerateKEMKeysRequest) (*EnumerateKEMKeysResponse, error)
	DestroyKEMKey(context.Context, *DestroyKEMKeyRequest) (*DestroyKEMKeyResponse, error)
	GetKEMKey(context.Context, *GetKEMKeyRequest) (*GetKEMKeyResponse, error)
	Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error)
}

// UnimplementedKeyProtectionServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyProtectionServiceServer struct{}

func (UnimplementedKeyProtectionServiceServer) GenerateKEMKeypair(context.Context, *GenerateKEMKeypairRequest) (*GenerateKEMKeypairResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GenerateKEMKeypair not implemented")
}
func (UnimplementedKeyProtectionServiceServer) DecapAndSeal(context.Context, *DecapAndSealRequest) (*DecapAndSealResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DecapAndSeal not implemented")
}
func (UnimplementedKeyProtectionServiceServer) EnumerateKEMKeys(context.Context, *EnumerateKEMKeysRequest) (*EnumerateKEMKeysResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method EnumerateKEMKeys not implemented")
}
func (UnimplementedKeyProtectionServiceServer) DestroyKEMKey(context.Context, *DestroyKEMKeyRequest) (*DestroyKEMKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method DestroyKEMKey not implemented")
}
func (UnimplementedKeyProtectionServiceServer) GetKEMKey(context.Context, *GetKEMKeyRequest) (*GetKEMKeyResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKEMKey not implemented")
}
func (UnimplementedKeyProtectionServiceServer) Heartbeat(context.Context, *HeartbeatRequest) (*HeartbeatResponse, error) {
	return nil, status.Errorf(codes.Unimplemented, "method Heartbeat not implemented")
}
func (UnimplementedKeyProtectionServiceServer) testEmbeddedByValue() {}

// UnsafeKeyProtectionServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyProtectionServiceServer will
// result in compilation errors.
type UnsafeKeyProtectionServiceServer interface {
	mustEmbedUnimplementedKeyProtectionServiceServer()
}

func RegisterKeyProtectionServiceServer(s grpc.ServiceRegistrar, srv KeyProtectionServiceServer) {
	// If the following call pancis, it indicates UnimplementedKeyProtectionServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyProtectionService_ServiceDesc, srv)
}

func _KeyProtectionService_GenerateKEMKeypair_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GenerateKEMKeypairRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyProtectionServiceServer).GenerateKEMKeypair(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyProtectionService_GenerateKEMKeypair_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyProtectionServiceServer).GenerateKEMKeypair(ctx, req.(*GenerateKEMKeypairRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyProtectionService_DecapAndSeal_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecapAndSealRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyProtectionServiceServer).DecapAndSeal(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyProtectionService_DecapAndSeal_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyProtectionServiceServer).DecapAndSeal(ctx, req.(*DecapAndSealRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyProtectionService_EnumerateKEMKeys_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EnumerateKEMKeysRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyProtectionServiceServer).EnumerateKEMKeys(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyProtectionService_EnumerateKEMKeys_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyProtectionServiceServer).EnumerateKEMKeys(ctx, req.(*EnumerateKEMKeysRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyProtectionService_DestroyKEMKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DestroyKEMKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyProtectionServiceServer).DestroyKEMKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyProtectionService_DestroyKEMKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyProtectionServiceServer).DestroyKEMKey(ctx, req.(*DestroyKEMKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyProtectionService_GetKEMKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKEMKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyProtectionServiceServer).GetKEMKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyProtectionService_GetKEMKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyProtectionServiceServer).GetKEMKey(ctx, req.(*GetKEMKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KeyProtectionService_Heartbeat_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(HeartbeatRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyProtectionServiceServer).Heartbeat(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyProtectionService_Heartbeat_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyProtectionServiceServer).Heartbeat(ctx, req.(*HeartbeatRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyProtectionService_ServiceDesc is the grpc.ServiceDesc for KeyProtectionService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyProtectionService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keymanager.key_protection_service.KeyProtectionService",
	HandlerType: (*KeyProtectionServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GenerateKEMKeypair",
			Handler:    _KeyProtectionService_GenerateKEMKeypair_Handler,
		},
		{
			MethodName: "DecapAndSeal",
			Handler:    _KeyProtectionService_DecapAndSeal_Handler,
		},
		{
			MethodName: "EnumerateKEMKeys",
			Handler:    _KeyProtectionService_EnumerateKEMKeys_Handler,
		},
		{
			MethodName: "DestroyKEMKey",
			Handler:    _KeyProtectionService_DestroyKEMKey_Handler,
		},
		{
			MethodName: "GetKEMKey",
			Handler:    _KeyProtectionService_GetKEMKey_Handler,
		},
		{
			MethodName: "Heartbeat",
			Handler:    _KeyProtectionService_Heartbeat_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "key_protection_service/proto/api.proto",
}
