// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.5.1
// - protoc             (unknown)
// source: km_common/proto/key_claims.proto

package keymanager

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KeyClaimsService_GetKeyClaims_FullMethodName = "/keymanager.KeyClaimsService/GetKeyClaims"
)

// KeyClaimsServiceClient is the client API for KeyClaimsService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// Service for retrieving key claims.
type KeyClaimsServiceClient interface {
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	GetKeyClaims(ctx context.Context, in *GetKeyClaimsRequest, opts ...grpc.CallOption) (*KeyClaims, error)
}

type keyClaimsServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKeyClaimsServiceClient(cc grpc.ClientConnInterface) KeyClaimsServiceClient {
	return &keyClaimsServiceClient{cc}
}

func (c *keyClaimsServiceClient) GetKeyClaims(ctx context.Context, in *GetKeyClaimsRequest, opts ...grpc.CallOption) (*KeyClaims, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(KeyClaims)
	err := c.cc.Invoke(ctx, KeyClaimsService_GetKeyClaims_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KeyClaimsServiceServer is the server API for KeyClaimsService service.
// All implementations should embed UnimplementedKeyClaimsServiceServer
// for forward compatibility.
//
// Service for retrieving key claims.
type KeyClaimsServiceServer interface {
	// buf:lint:ignore RPC_RESPONSE_STANDARD_NAME
	GetKeyClaims(context.Context, *GetKeyClaimsRequest) (*KeyClaims, error)
}

// UnimplementedKeyClaimsServiceServer should be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKeyClaimsServiceServer struct{}

func (UnimplementedKeyClaimsServiceServer) GetKeyClaims(context.Context, *GetKeyClaimsRequest) (*KeyClaims, error) {
	return nil, status.Errorf(codes.Unimplemented, "method GetKeyClaims not implemented")
}
func (UnimplementedKeyClaimsServiceServer) testEmbeddedByValue() {}

// UnsafeKeyClaimsServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KeyClaimsServiceServer will
// result in compilation errors.
type UnsafeKeyClaimsServiceServer interface {
	mustEmbedUnimplementedKeyClaimsServiceServer()
}

func RegisterKeyClaimsServiceServer(s grpc.ServiceRegistrar, srv KeyClaimsServiceServer) {
	// If the following call pancis, it indicates UnimplementedKeyClaimsServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KeyClaimsService_ServiceDesc, srv)
}

func _KeyClaimsService_GetKeyClaims_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyClaimsRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KeyClaimsServiceServer).GetKeyClaims(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KeyClaimsService_GetKeyClaims_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KeyClaimsServiceServer).GetKeyClaims(ctx, req.(*GetKeyClaimsRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KeyClaimsService_ServiceDesc is the grpc.ServiceDesc for KeyClaimsService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KeyClaimsService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "keymanager.KeyClaimsService",
	HandlerType: (*KeyClaimsServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "GetKeyClaims",
			Handler:    _KeyClaimsService_GetKeyClaims_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "km_common/proto/key_claims.proto",
}
