package workloadservice

import (
	"bytes"
	"context"
	"encoding/json"
	"errors"
	"fmt"
	"io"
	"net"
	"net/http"
	"net/http/httptest"
	"os"
	"path/filepath"
	"strings"
	"testing"
	"time"

	"github.com/google/uuid"
	"google.golang.org/grpc"
	"google.golang.org/grpc/credentials/insecure"

	kpskcc "github.com/GoogleCloudPlatform/key-protection-module/key_protection_service/key_custody_core"
	keymanager "github.com/GoogleCloudPlatform/key-protection-module/km_common/proto"

	kps "github.com/GoogleCloudPlatform/key-protection-module/key_protection_service"
	kpspb "github.com/GoogleCloudPlatform/key-protection-module/key_protection_service/proto"
)

// TestIntegrationGRPC_EndToEnd spins up a live KPS gRPC server and a WSD server,
// and verifies communication between them.
func TestIntegrationGRPC_EndToEnd(t *testing.T) {
	// 1. Start a TCP listener on a free port
	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("failed to listen on tcp: %v", err)
	}

	// 2. Instantiate key_protection_service.NewService()
	kpsSvc := kps.NewService()

	// 3. Instantiate key_protection_service.NewGrpcServer()
	kpsGrpcServer := kps.NewGrpcServer(kpsSvc, "test-boot-token")

	// 4. Register the server and serve in a background goroutine
	grpcServer := grpc.NewServer()
	kpspb.RegisterKeyProtectionServiceServer(grpcServer, kpsGrpcServer)
	// Serve always returns an error when Stop is called; ignore.
	go func() { _ = grpcServer.Serve(listener) }()
	defer grpcServer.Stop()

	// 5. Create a gRPC client connection to that listener
	conn, err := grpc.NewClient(listener.Addr().String(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		t.Fatalf("failed to dial grpc server: %v", err)
	}
	defer func() { _ = conn.Close() }()

	// 6. Instantiate the remoteKeyProtectionService with that client
	kpsClient := kpspb.NewKeyProtectionServiceClient(conn)
	remoteKps := NewRemoteKeyProtectionService(kpsClient)

	// 7. Start the WSD HTTP server (using the remoteKeyProtectionService)
	// We use a mock WorkloadService since this test focuses on KPS integration.
	mockWsd := &mockWorkloadService{uuid: uuid.New(), pubKey: []byte("thirty-two-bytes-of-dummy-pubkey")}
	wsdServer, err := NewServer(remoteKps, mockWsd, filepath.Join(t.TempDir(), "test.sock"))
	if err != nil {
		t.Fatalf("failed to create wsd server: %v", err)
	}
	defer func() {
		_ = wsdServer.Shutdown(context.Background())
	}()

	ts := httptest.NewServer(wsdServer.Handler())
	defer ts.Close()

	client := ts.Client()

	// --- 8. Make HTTP requests to exercise the full flow ---

	// A. Generate Key
	genReqBody := []byte(`{"algorithm":{"type":"kem","params":{"kemId":"KEM_ALGORITHM_DHKEM_X25519_HKDF_SHA256"}},"lifespan":3600}`)
	genResp, err := client.Post(ts.URL+"/v1/keys:generate_key", "application/json", bytes.NewReader(genReqBody))
	if err != nil {
		t.Fatalf("Generate Key request failed: %v", err)
	}
	if genResp.StatusCode != http.StatusOK {
		t.Fatalf("Generate Key expected status 200, got %d: body %v", genResp.StatusCode, string(func() []byte { b, _ := io.ReadAll(genResp.Body); return b }()))
	}
	var genResMap map[string]interface{}
	if err := json.NewDecoder(genResp.Body).Decode(&genResMap); err != nil {
		t.Fatalf("Failed to decode Generate Key response: %v", err)
	}
	_ = genResp.Body.Close()

	keyHandleObj, ok := genResMap["key_handle"].(map[string]interface{})
	if !ok {
		t.Fatalf("Response missing key_handle map")
	}
	kemUUIDStr, ok := keyHandleObj["handle"].(string)
	if !ok || kemUUIDStr == "" {
		t.Fatalf("Response missing handle string")
	}

	// B. Enumerate Keys
	enumResp, err := client.Get(ts.URL + "/v1/keys")
	if err != nil {
		t.Fatalf("Enumerate Keys request failed: %v", err)
	}
	if enumResp.StatusCode != http.StatusOK {
		t.Fatalf("Enumerate Keys expected status 200, got %d", enumResp.StatusCode)
	}
	var enumResMap map[string]interface{}
	if err := json.NewDecoder(enumResp.Body).Decode(&enumResMap); err != nil {
		t.Fatalf("Failed to decode Enumerate Keys response: %v", err)
	}
	_ = enumResp.Body.Close()

	// Ensure the generated key is in the list
	keysList, ok := enumResMap["key_infos"].([]interface{})
	if !ok {
		t.Fatalf("Enumerate Keys response missing keys array: %v", enumResMap)
	}
	found := false
	for _, keyItem := range keysList {
		keyObj, ok := keyItem.(map[string]interface{})
		if !ok {
			continue
		}
		khObj, ok := keyObj["key_handle"].(map[string]interface{})
		if !ok {
			continue
		}
		if khObj["handle"] == kemUUIDStr {
			found = true
			break
		}
	}
	if !found {
		t.Fatalf("Generated key %s not found in Enumerate Keys response", kemUUIDStr)
	}

	// C. Decaps
	// Since we don't have a valid ciphertext generated by Tink/BoringCrypto,
	// DecapAndSeal will fail in KPS Core (FFI), returning an error. WSD should surface this as 500.
	decapReqBody := []byte(`{
		"key_handle": {"handle": "` + kemUUIDStr + `"},
		"ciphertext": {
			"algorithm": "KEM_ALGORITHM_DHKEM_X25519_HKDF_SHA256",
			"ciphertext": "invalid-ciphertext-data-that-is-long-enough-to-pass-basic-checks"
		}
	}`)
	decapResp, err := client.Post(ts.URL+"/v1/keys:decap", "application/json", bytes.NewReader(decapReqBody))
	if err != nil {
		t.Fatalf("Decap request failed: %v", err)
	}
	_ = decapResp.Body.Close()

	// Expect 500 because the ciphertext is invalid
	if decapResp.StatusCode != http.StatusInternalServerError {
		t.Fatalf("Decap expected status 500, got %d", decapResp.StatusCode)
	}

	// D. Destroy Key
	destroyReqBody := []byte(`{"key_handle": {"handle": "` + kemUUIDStr + `"}}`)
	destroyResp, err := client.Post(ts.URL+"/v1/keys:destroy", "application/json", bytes.NewReader(destroyReqBody))
	if err != nil {
		t.Fatalf("Destroy request failed: %v", err)
	}
	_ = destroyResp.Body.Close()
	if destroyResp.StatusCode != http.StatusNoContent {
		t.Fatalf("Destroy expected status 204, got %d", destroyResp.StatusCode)
	}
}

// stubKPS lets a test inject error returns into the gRPC server, one per RPC.
// All errors default to nil so a zero-value stub behaves as a successful backend.
type stubKPS struct {
	generateErr  error
	decapErr     error
	enumerateErr error
	destroyErr   error
	getErr       error
}

func (s *stubKPS) GenerateKEMKeypair(_ context.Context, _ *keymanager.HpkeAlgorithm, _ []byte, _ uint64) (uuid.UUID, []byte, error) {
	if s.generateErr != nil {
		return uuid.Nil, nil, s.generateErr
	}
	return uuid.New(), make([]byte, 32), nil
}
func (s *stubKPS) DecapAndSeal(_ context.Context, _ uuid.UUID, _, _ []byte) ([]byte, []byte, error) {
	if s.decapErr != nil {
		return nil, nil, s.decapErr
	}
	return nil, nil, nil
}
func (s *stubKPS) EnumerateKEMKeys(_ context.Context, _, _ int32) ([]kpskcc.KEMKeyInfo, bool, error) {
	if s.enumerateErr != nil {
		return nil, false, s.enumerateErr
	}
	return nil, false, nil
}
func (s *stubKPS) DestroyKEMKey(_ context.Context, _ uuid.UUID) error {
	return s.destroyErr
}
func (s *stubKPS) GetKEMKey(_ context.Context, _ uuid.UUID) ([]byte, []byte, *keymanager.HpkeAlgorithm, uint64, error) {
	if s.getErr != nil {
		return nil, nil, nil, 0, s.getErr
	}
	return nil, nil, nil, 0, nil
}

// setupGRPCRoundTrip wires a stub KPS backend → gRPC server → gRPC client → WSD HTTP server
// and returns the test HTTP server. If kemUUID is non-zero, the WSD's
// kemToBindingMap is pre-populated so handlers reach KPS instead of
// short-circuiting on their own "not found" check.
func setupGRPCRoundTrip(t *testing.T, stub kps.KeyProtectionService, kemUUID uuid.UUID) *httptest.Server {
	t.Helper()

	listener, err := net.Listen("tcp", "127.0.0.1:0")
	if err != nil {
		t.Fatalf("failed to listen on tcp: %v", err)
	}

	grpcServer := grpc.NewServer()
	kpspb.RegisterKeyProtectionServiceServer(grpcServer, kps.NewGrpcServer(stub, "test-boot-token"))
	go func() { _ = grpcServer.Serve(listener) }()
	t.Cleanup(grpcServer.Stop)

	conn, err := grpc.NewClient(listener.Addr().String(), grpc.WithTransportCredentials(insecure.NewCredentials()))
	if err != nil {
		t.Fatalf("failed to dial grpc server: %v", err)
	}
	t.Cleanup(func() { _ = conn.Close() })

	remoteKps := NewRemoteKeyProtectionService(kpspb.NewKeyProtectionServiceClient(conn))
	mockWsd := &mockWorkloadService{uuid: uuid.New(), pubKey: []byte("thirty-two-bytes-of-dummy-pubkey")}

	// macOS sockaddr_un caps sun_path at 104 chars; t.TempDir() can exceed that
	// for tests with long names, so use a short hand-rolled tmp path.
	sockDir, err := os.MkdirTemp("", "kps-")
	if err != nil {
		t.Fatalf("mkdir temp: %v", err)
	}
	t.Cleanup(func() { _ = os.RemoveAll(sockDir) })

	wsdServer, err := NewServer(remoteKps, mockWsd, filepath.Join(sockDir, "s"))
	if err != nil {
		t.Fatalf("failed to create wsd server: %v", err)
	}
	t.Cleanup(func() {
		_ = wsdServer.Shutdown(context.Background())
	})

	if kemUUID != uuid.Nil {
		wsdServer.mu.Lock()
		wsdServer.kemToBindingMap[kemUUID] = mockWsd.uuid
		wsdServer.mu.Unlock()
	}

	ts := httptest.NewServer(wsdServer.Handler())
	t.Cleanup(ts.Close)
	return ts
}

// TestIntegrationGRPC_ErrorCodeRoundTrip verifies that FFI status errors from
// the KPS backend are mapped to a gRPC code on the wire and back to the
// matching HTTP status by the WSD adapter — i.e. they do NOT collapse to 500.
// Covers the four RPCs reachable from the WSD HTTP API and a representative
// sampling of FFI status codes.
func TestIntegrationGRPC_ErrorCodeRoundTrip(t *testing.T) {
	kemUUID := uuid.New()
	destroyBody := `{"key_handle": {"handle": "` + kemUUID.String() + `"}}`
	decapBody := `{"key_handle": {"handle": "` + kemUUID.String() + `"}, ` +
		`"ciphertext": {"algorithm": "KEM_ALGORITHM_DHKEM_X25519_HKDF_SHA256", ` +
		`"ciphertext": "ZmFrZS1jaXBoZXJ0ZXh0LWxvbmctZW5vdWdo"}}`
	generateBody := `{"algorithm":{"type":"kem","params":` +
		`{"kemId":"KEM_ALGORITHM_DHKEM_X25519_HKDF_SHA256"}},"lifespan":3600}`

	cases := []struct {
		name           string
		stub           stubKPS
		method, path   string
		body           string
		wantHTTPStatus int
	}{
		{
			name:           "destroy_not_found_to_404",
			stub:           stubKPS{destroyErr: keymanager.Status_STATUS_NOT_FOUND.ToStatus()},
			method:         http.MethodPost,
			path:           "/v1/keys:destroy",
			body:           destroyBody,
			wantHTTPStatus: http.StatusNotFound,
		},
		{
			name:           "destroy_invalid_argument_to_400",
			stub:           stubKPS{destroyErr: keymanager.Status_STATUS_INVALID_ARGUMENT.ToStatus()},
			method:         http.MethodPost,
			path:           "/v1/keys:destroy",
			body:           destroyBody,
			wantHTTPStatus: http.StatusBadRequest,
		},
		{
			name:           "destroy_permission_denied_to_403",
			stub:           stubKPS{destroyErr: keymanager.Status_STATUS_PERMISSION_DENIED.ToStatus()},
			method:         http.MethodPost,
			path:           "/v1/keys:destroy",
			body:           destroyBody,
			wantHTTPStatus: http.StatusForbidden,
		},
		{
			name:           "destroy_unauthenticated_to_401",
			stub:           stubKPS{destroyErr: keymanager.Status_STATUS_UNAUTHENTICATED.ToStatus()},
			method:         http.MethodPost,
			path:           "/v1/keys:destroy",
			body:           destroyBody,
			wantHTTPStatus: http.StatusUnauthorized,
		},
		{
			name:           "destroy_already_exists_to_409",
			stub:           stubKPS{destroyErr: keymanager.Status_STATUS_ALREADY_EXISTS.ToStatus()},
			method:         http.MethodPost,
			path:           "/v1/keys:destroy",
			body:           destroyBody,
			wantHTTPStatus: http.StatusConflict,
		},
		{
			name:           "destroy_crypto_error_to_500",
			stub:           stubKPS{destroyErr: keymanager.Status_STATUS_CRYPTO_ERROR.ToStatus()},
			method:         http.MethodPost,
			path:           "/v1/keys:destroy",
			body:           destroyBody,
			wantHTTPStatus: http.StatusInternalServerError,
		},
		{
			name:           "decap_not_found_to_404",
			stub:           stubKPS{decapErr: keymanager.Status_STATUS_NOT_FOUND.ToStatus()},
			method:         http.MethodPost,
			path:           "/v1/keys:decap",
			body:           decapBody,
			wantHTTPStatus: http.StatusNotFound,
		},
		{
			name:           "decap_invalid_key_to_400",
			stub:           stubKPS{decapErr: keymanager.Status_STATUS_INVALID_KEY.ToStatus()},
			method:         http.MethodPost,
			path:           "/v1/keys:decap",
			body:           decapBody,
			wantHTTPStatus: http.StatusBadRequest,
		},
		{
			name:           "enumerate_invalid_argument_to_400",
			stub:           stubKPS{enumerateErr: keymanager.Status_STATUS_INVALID_ARGUMENT.ToStatus()},
			method:         http.MethodGet,
			path:           "/v1/keys",
			body:           "",
			wantHTTPStatus: http.StatusBadRequest,
		},
		{
			name:           "generate_unsupported_algorithm_to_400",
			stub:           stubKPS{generateErr: keymanager.Status_STATUS_UNSUPPORTED_ALGORITHM.ToStatus()},
			method:         http.MethodPost,
			path:           "/v1/keys:generate_key",
			body:           generateBody,
			wantHTTPStatus: http.StatusBadRequest,
		},
	}

	for _, tc := range cases {
		t.Run(tc.name, func(t *testing.T) {
			stub := tc.stub
			ts := setupGRPCRoundTrip(t, &stub, kemUUID)

			req, err := http.NewRequest(tc.method, ts.URL+tc.path, strings.NewReader(tc.body))
			if err != nil {
				t.Fatalf("NewRequest: %v", err)
			}
			if tc.body != "" {
				req.Header.Set("Content-Type", "application/json")
			}
			resp, err := ts.Client().Do(req)
			if err != nil {
				t.Fatalf("request failed: %v", err)
			}
			defer func() { _ = resp.Body.Close() }()

			if resp.StatusCode != tc.wantHTTPStatus {
				respBody, _ := io.ReadAll(resp.Body)
				t.Fatalf("got HTTP %d, want %d: %s", resp.StatusCode, tc.wantHTTPStatus, respBody)
			}
		})
	}
}

// fakeKPSClient is a hand-rolled kpspb.KeyProtectionServiceClient that lets a
// test return an arbitrary GenerateKEMKeypair response — including malformed
// payloads (e.g. non-UUID handles) that a real server wouldn't produce, but
// that the client adapter must still defend against.
type fakeKPSClient struct {
	generateResp *kpspb.GenerateKEMKeypairResponse
	generateErr  error
	delay        time.Duration
}

func (f *fakeKPSClient) GenerateKEMKeypair(ctx context.Context, _ *kpspb.GenerateKEMKeypairRequest, _ ...grpc.CallOption) (*kpspb.GenerateKEMKeypairResponse, error) {
	if f.delay > 0 {
		select {
		case <-time.After(f.delay):
		case <-ctx.Done():
			return nil, fmt.Errorf("context error: %w", ctx.Err())
		}
	}
	return f.generateResp, f.generateErr
}
func (f *fakeKPSClient) DecapAndSeal(context.Context, *kpspb.DecapAndSealRequest, ...grpc.CallOption) (*kpspb.DecapAndSealResponse, error) {
	return nil, nil
}
func (f *fakeKPSClient) EnumerateKEMKeys(context.Context, *kpspb.EnumerateKEMKeysRequest, ...grpc.CallOption) (*kpspb.EnumerateKEMKeysResponse, error) {
	return nil, nil
}
func (f *fakeKPSClient) DestroyKEMKey(context.Context, *kpspb.DestroyKEMKeyRequest, ...grpc.CallOption) (*kpspb.DestroyKEMKeyResponse, error) {
	return nil, nil
}
func (f *fakeKPSClient) GetKEMKey(context.Context, *kpspb.GetKEMKeyRequest, ...grpc.CallOption) (*kpspb.GetKEMKeyResponse, error) {
	return nil, nil
}
func (f *fakeKPSClient) Heartbeat(context.Context, *kpspb.HeartbeatRequest, ...grpc.CallOption) (*kpspb.HeartbeatResponse, error) {
	return nil, nil
}

// TestRemoteKeyProtectionService_GenerateKEMKeypair_BadHandle verifies that the
// WSD client adapter rejects a malformed (non-UUID) key handle returned by a
// misbehaving KPS instead of propagating uuid.Nil silently.
func TestRemoteKeyProtectionService_GenerateKEMKeypair_BadHandle(t *testing.T) {
	fake := &fakeKPSClient{
		generateResp: &kpspb.GenerateKEMKeypairResponse{
			KeyHandle: &keymanager.KeyHandle{Handle: "not-a-valid-uuid"},
			KemPubKey: &keymanager.KemPublicKey{
				Algorithm: keymanager.KemAlgorithm_KEM_ALGORITHM_DHKEM_X25519_HKDF_SHA256,
				PublicKey: make([]byte, 32),
			},
		},
	}

	remote := NewRemoteKeyProtectionService(fake)
	id, pubKey, err := remote.GenerateKEMKeypair(context.Background(),
		&keymanager.HpkeAlgorithm{Kem: keymanager.KemAlgorithm_KEM_ALGORITHM_DHKEM_X25519_HKDF_SHA256},
		make([]byte, 32), 3600)

	if err == nil {
		t.Fatalf("expected error for malformed handle, got nil (id=%s, pubKey=%v)", id, pubKey)
	}
	if !strings.Contains(err.Error(), "invalid KEM key handle from server") {
		t.Errorf("expected wrapped 'invalid KEM key handle from server' error, got: %v", err)
	}
	if id != uuid.Nil {
		t.Errorf("expected uuid.Nil on error, got %s", id)
	}
}

func TestRemoteKeyProtectionService_GenerateKEMKeypair_Timeout(t *testing.T) {
	fake := &fakeKPSClient{
		delay: 2 * RPCTimeout, // Longer than the timeout
		generateResp: &kpspb.GenerateKEMKeypairResponse{
			KeyHandle: &keymanager.KeyHandle{Handle: uuid.New().String()},
			KemPubKey: &keymanager.KemPublicKey{
				Algorithm: keymanager.KemAlgorithm_KEM_ALGORITHM_DHKEM_X25519_HKDF_SHA256,
				PublicKey: make([]byte, 32),
			},
		},
	}

	remote := NewRemoteKeyProtectionService(fake)
	_, _, err := remote.GenerateKEMKeypair(context.Background(),
		&keymanager.HpkeAlgorithm{Kem: keymanager.KemAlgorithm_KEM_ALGORITHM_DHKEM_X25519_HKDF_SHA256},
		make([]byte, 32), 3600)

	if err == nil {
		t.Fatalf("expected timeout error, got nil")
	}
	if !errors.Is(err, context.DeadlineExceeded) && !strings.Contains(err.Error(), "context deadline exceeded") {
		t.Errorf("expected timeout error, got: %v", err)
	}
}
